import { expect, test } from '@playwright/test'

test.use({ viewport: { width: 1440, height: 900 } })

test('keeps the successful channel and draft while retrying Knowledge hydration', async ({ page }) => {
  await page.goto('http://127.0.0.1:6007/iframe.html?id=dots-knowledgesurface--hydration-recovery&viewMode=story', { waitUntil: 'domcontentloaded' })
  const alert = page.getByRole('alert')
  await expect(alert).toBeVisible()
  const list = page.locator('section[aria-labelledby="knowledge-heading"] ol')
  await expect(list).toContainText('hydration.pdf')
  const initialItems = await list.locator('li').count()
  const composer = page.locator('#knowledge-composer')
  await composer.fill('再試行しても残る下書き')
  await alert.getByRole('button').click()
  await expect(composer).toBeDisabled()
  await expect(composer).toHaveValue('再試行しても残る下書き')
  const composerBox = await composer.locator('xpath=..').boundingBox()
  const sidebarBox = await page.locator('#workspace-sidebar').boundingBox()
  const mainBox = await page.locator('.workspace-shell__main').boundingBox()
  expect(sidebarBox?.width).toBe(168)
  expect(composerBox?.width).toBeGreaterThanOrEqual(760)
  expect(composerBox?.width).toBeLessThanOrEqual(960)
  expect(composerBox?.x).toBeGreaterThanOrEqual((sidebarBox?.x ?? 0) + (sidebarBox?.width ?? 0))
  expect(Math.abs(((composerBox?.x ?? 0) + (composerBox?.width ?? 0) / 2) - ((mainBox?.x ?? 0) + (mainBox?.width ?? 0) / 2))).toBeLessThanOrEqual(2)
  expect((composerBox?.y ?? 0) + (composerBox?.height ?? 0)).toBeLessThanOrEqual(900)
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(composer).toBeEnabled()
  await expect(composer).toHaveValue('再試行しても残る下書き')
  await expect(list.locator('li')).toHaveCount(initialItems + 1)
  await expect(list).toContainText('hydration.pdf')
  await page.screenshot({ path: 'test-results/knowledge-hydration-recovery-1440.png', fullPage: false })
})
