import { useEffect, useMemo, useState } from 'react';
import { createLocalContextSnapshot } from '../context/contextSnapshot';

const storageKey = 'kadode:home-supervisor';
const initialSnapshot = createLocalContextSnapshot({ ownerId: 'local-owner', surface: { name: 'Home', route: '/home' } });

export function proposeHomeAction(input, snapshot = initialSnapshot) {
  const action = /情報|プロフィール/.test(input) ? 'update_profile' : /プロジェクト|一覧/.test(input) ? 'inspect_projects' : /却下/.test(input) ? 'reject_candidate' : /保留/.test(input) ? 'hold_candidate' : /採用/.test(input) ? 'adopt_candidate' : 'ideate';
  return { id: crypto.randomUUID(), fact: `現在のsurface: ${snapshot.surface.name}`, inference: `入力を「${action}」として整理しました。`, action, confirmed: false };
}

export function createHomeSupervisorRepository(storage = globalThis.localStorage) {
  return { load: async () => { try { const value = JSON.parse(storage?.getItem(storageKey) || '{"messages":[],"proposals":[]}'); return value && Array.isArray(value.messages) && Array.isArray(value.proposals) ? value : { messages: [], proposals: [], input: '' }; } catch { return { messages: [], proposals: [], input: '' }; } }, save: async (value) => { storage?.setItem(storageKey, JSON.stringify(value)); return value; } };
}

export function HomeSupervisor({ repository, snapshot = initialSnapshot, onProjectAdopt }) {
  const [browserRepository] = useState(() => createHomeSupervisorRepository()); const activeRepository = repository ?? browserRepository;
  const [state, setState] = useState({ messages: [], proposals: [], input: '' }); const [input, setInput] = useState(''); const [rejectReason, setRejectReason] = useState(''); const [error, setError] = useState('');
  useEffect(() => { activeRepository.load().then((value) => { setState(value); setInput(value.input || ''); }).catch(() => setError('会話を読み込めませんでした。')); }, [activeRepository]);
  const context = useMemo(() => JSON.stringify(snapshot), [snapshot]);
  async function send(event) { event.preventDefault(); const text = input.trim(); if (!text) return setError('発言を入力してください。'); const proposal = proposeHomeAction(text, snapshot); const next = { messages: [...state.messages, { role: 'user', content: text }], proposals: [proposal, ...state.proposals], input: '' }; try { await activeRepository.save(next); setState(next); setInput(''); setError(''); } catch { setError('端末内に保存できませんでした。'); } }
  async function decide(id, decision) { if (decision === 'rejected' && !rejectReason.trim()) return setError('却下理由を入力してください。'); const next = { ...state, proposals: state.proposals.map((proposal) => proposal.id === id ? { ...proposal, status: decision, confirmed: decision === 'adopted', ...(decision === 'rejected' ? { rejectionReason: rejectReason.trim() } : {}) } : proposal) }; try { await activeRepository.save(next); setState(next); setRejectReason(''); setError(''); if (decision === 'adopted') onProjectAdopt?.(next.proposals.find((proposal) => proposal.id === id)); } catch { setError('判断を保存できませんでした。'); } }
  return <section aria-labelledby="home-supervisor-heading" className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-stone-500">Home</p><h1 id="home-supervisor-heading" className="mt-2 text-2xl font-semibold tracking-tight">Kadode AI</h1><p className="mt-2 text-sm text-stone-600">portfolio全体の次の検討を整理します。</p><form onSubmit={send} className="mt-6 rounded-2xl border border-stone-300 bg-white p-3"><label htmlFor="home-supervisor-message" className="sr-only">Kadode AIへのメッセージ</label><textarea id="home-supervisor-message" value={input} onChange={(event) => { const value = event.target.value; setInput(value); void activeRepository.save({ ...state, input: value }).catch(() => setError('入力を端末内に保存できませんでした。')); }} className="min-h-24 w-full resize-y p-2 text-base leading-6 outline-none" placeholder="アイデア、情報更新、プロジェクト確認を話してみる" /><p className="mt-2 text-xs text-stone-500">Enterで送信、Shift+Enterで改行</p><button className="mt-2 min-h-11 rounded-full bg-stone-900 px-5 py-2 text-sm font-bold text-white">発言を送信</button></form><div className="sr-only" data-testid="context-snapshot" data-owner={snapshot.ownerId} data-surface={snapshot.surface.name}>現在のページ: {snapshot.surface.name}</div><div className="mt-5 grid gap-3">{state.proposals.map((proposal) => <article key={proposal.id} className="rounded-2xl border p-4"><p><strong>事実:</strong> {proposal.fact}</p><p><strong>推論:</strong> {proposal.inference}</p><p><strong>操作:</strong> {proposal.action}</p>{proposal.status === 'adopted' ? <p role="status">Projectへ採用済み</p> : proposal.status === 'held' ? <p role="status">保留中</p> : proposal.status === 'rejected' ? <p role="status">却下: {proposal.rejectionReason}</p> : <><label htmlFor={`reject-${proposal.id}`}>却下理由（却下時は必須）</label><textarea id={`reject-${proposal.id}`} value={rejectReason} onChange={(event) => setRejectReason(event.target.value)} rows={2} className="mt-2 w-full rounded-xl border p-2" /><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => decide(proposal.id, 'adopted')} className="min-h-11 rounded-full bg-stone-900 px-4 py-2 font-bold text-white">プロジェクトに採用</button><button type="button" onClick={() => decide(proposal.id, 'held')} className="min-h-11 rounded-full border px-4 py-2 font-bold">保留</button><button type="button" onClick={() => decide(proposal.id, 'rejected')} className="min-h-11 rounded-full border border-red-700 px-4 py-2 font-bold text-red-800">理由付きで却下</button></div></>}</article>)}</div>{error && <p role="alert">{error}</p>}</section>;
}
