import { IdeaCandidateWorkspace } from './IdeaCandidateWorkspace';
const item = { id: 'demo', title: '工場ノート', summary: '設備保全を記録', pain: '履歴が探せない' };
const repository = (items = [], fails = false) => ({ load: async () => items, save: async (next) => { if (fails) throw new Error('offline'); return next; } });
export default { title: 'Kadode/IdeaCandidateWorkspace', component: IdeaCandidateWorkspace, parameters: { layout: 'padded' } };
const conversationRepository = (messages = []) => ({ load: async () => messages, save: async (next) => next });
export const Desktop = { args: { repository: repository([item]), conversationRepository } };
export const Mobile = { args: { repository: repository([item]), conversationRepository }, parameters: { viewport: { defaultViewport: 'mobile1' } } };
export const Empty = { args: { repository: repository(), conversationRepository } };
export const ConversationReady = { args: { repository: repository(), conversationRepository: conversationRepository([{ role: 'user', content: '工場の保全担当者が履歴を探せず困っています' }, { role: 'assistant', content: 'その困りごとを、どんな方法で解決する案ですか？' }]) } };
export const Duplicate = { args: { repository: repository([item]), conversationRepository: conversationRepository([{ role: 'user', content: '工場ノート' }]) } };
export const SaveError = { args: { repository: repository([], true), conversationRepository } };
