import { useEffect, useMemo, useRef, useState } from 'react';
import { Search, SendHorizontal, Upload } from 'lucide-react';
import { AiComposer } from './AiComposer';
import { Badge } from './ui/Badge';
import { Button } from './ui/Button';
import { Card } from './ui/Card';
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogTitle } from './ui/Dialog';
import { createKnowledgeMetadataRepository } from './knowledgeMetadataRepository';
import { createKnowledgeConversationRepository, proposeKnowledgeEntry, respondToKnowledge } from './knowledgeConversationRepository';

const MAX_FILE_SIZE = 10 * 1024 * 1024;
const categoryLabel = { all: 'すべて', profile: 'プロフィール', decision: '意思決定', conversation: '過去の会話', file: 'ファイル', note: 'メモ' };
const stateLabel = { metadata_only: 'メタデータのみ', processing: '処理中', searchable: '検索可能', failed: '確認が必要' };

export function createLocalUploadMetadata(file) {
  const name = String(file?.name ?? '').trim(); const extension = name.split('.').at(-1)?.toLowerCase();
  if (!['pdf', 'docx'].includes(extension)) throw new Error('PDFまたはDOCXを選択してください。');
  if (!Number.isFinite(file?.size) || file.size > MAX_FILE_SIZE) throw new Error('10 MiB以下のファイルを選択してください。');
  const lastModified = Number.isFinite(file?.lastModified) ? file.lastModified : 0;
  return { id: `local-file:${encodeURIComponent(name.toLocaleLowerCase())}:${file.size}:${lastModified}`, name, version: 1, state: 'metadata_only', mediaType: extension, sizeBytes: file.size, lastModified, extractedTextState: 'pending', indexState: 'pending' };
}

const dateText = (value) => {
  const date = new Date(value);
  return Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat('ja-JP', { month: 'short', day: 'numeric' }).format(date) : '日付未確認';
};
const sourceLabel = { synthetic: '画面生成', local: 'この端末', unknown: '出典未確認' };
const confidenceLabel = { high: '高', medium: '中', unknown: '未確認' };

export function KnowledgeSurface({ fixture, repository, conversationRepository, profile, archiveHistory = [], ownerId = 'admin-demo-owner', spaceId = 'admin-demo-space', onSend = () => {}, onAssetAdded = () => {}, onOpenProject = () => {}, modelKey = 'gpt-5.6-terra', models = [], onModelChange }) {
  const [message, setMessage] = useState(''); const [documents, setDocuments] = useState([]); const [state, setState] = useState({ messages: [], entries: [] });
  const [candidate, setCandidate] = useState(null); const [category, setCategory] = useState('all'); const [query, setQuery] = useState(''); const [removeRequested, setRemoveRequested] = useState(null); const [notice, setNotice] = useState('');
  const repositoryRef = useRef(repository ?? createKnowledgeMetadataRepository({ ownerId, spaceId })); const conversationRepositoryRef = useRef(conversationRepository ?? createKnowledgeConversationRepository({ ownerId, spaceId })); const fileInputRef = useRef(null); const dirtyRef = useRef(false); const loadGenerationRef = useRef(0);
  useEffect(() => { let active = true; const generation = ++loadGenerationRef.current; Promise.all([repositoryRef.current.load(), conversationRepositoryRef.current.load()]).then(([, saved]) => { if (active && generation === loadGenerationRef.current && !dirtyRef.current) { setDocuments(repositoryRef.current.list().filter((item) => item.state !== 'deleted')); setState({ messages: Array.isArray(saved?.messages) ? saved.messages : [], entries: Array.isArray(saved?.entries) ? saved.entries : [] }); } }).catch(() => active && setNotice('保存状態を読み込めませんでした。')); return () => { active = false; }; }, []);
  const items = useMemo(() => {
    const fixtureFile = fixture?.asset ? [{ id: fixture.asset.id, category: 'file', title: fixture.asset.name, content: 'プロジェクトに紐づく参照資料', createdAt: fixture.asset.updatedAt ?? new Date().toISOString(), state: fixture.asset.state, sourceType: 'synthetic', confidence: 'unknown', unknowns: [] }] : [];
    const files = documents.map((file) => ({ id: file.id, category: 'file', title: file.name, content: `${file.mediaType?.toUpperCase() ?? '資料'} · ${Math.max(1, Math.ceil((file.sizeBytes ?? 0) / 1024))} KB`, createdAt: new Date(file.lastModified ?? 0).toISOString(), state: file.state, sourceType: 'local', confidence: 'unknown', unknowns: [] }));
    const decision = fixture?.decision ? [{ id: `decision:${fixture.decision.id ?? 'current'}`, category: 'decision', title: fixture.decision.judgement, content: `${fixture.decision.background} ${fixture.decision.reason}`, createdAt: fixture.decision.date ?? '2026-01-01T00:00:00.000Z', sourceType: 'unknown', confidence: 'unknown', unknowns: [] }] : [];
    const profileEntry = profile?.status === 'completed' ? [{ id: 'profile:completed', category: 'profile', title: '完了プロフィール', content: Object.values(profile.values ?? {}).filter((value) => typeof value === 'string' && value.trim()).join(' · '), createdAt: profile.completedAt ?? profile.updatedAt ?? '2026-01-01T00:00:00.000Z', sourceType: 'unknown', confidence: 'unknown', unknowns: [] }] : [];
    const conversations = state.messages.filter((entry) => entry.role === 'user').map((entry, index) => ({ id: `conversation:${index}:${entry.content}`, category: 'conversation', title: entry.content.slice(0, 72), content: 'Kadode AIとの過去の会話', createdAt: entry.createdAt ?? '1970-01-01T00:00:00.000Z', sourceType: 'unknown', confidence: 'unknown', unknowns: [] }));
    const archived = archiveHistory.map((entry) => ({ id: `archive:${entry.id}`, category: 'conversation', title: entry.title, content: 'アーカイブ済みの会話またはプロジェクト', createdAt: entry.archivedAt ?? '1970-01-01T00:00:00.000Z', sourceType: 'unknown', confidence: 'unknown', unknowns: [] }));
    return [...state.entries, ...profileEntry, ...decision, ...fixtureFile, ...files, ...conversations, ...archived].map((entry) => ({ sourceType: 'unknown', confidence: 'unknown', unknowns: [], updatedAt: entry.createdAt, projectId: '', evaluationView: '', ...entry })).filter((entry) => (category === 'all' || entry.category === category) && `${entry.title} ${entry.content} ${entry.sourceType} ${entry.unknowns.join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
  }, [archiveHistory, category, documents, fixture, profile, query, state]);
  const save = async (next) => { dirtyRef.current = true; ++loadGenerationRef.current; await conversationRepositoryRef.current.save(next); setState(next); };
  function submit() { const value = message.trim(); if (!value) return; setCandidate(proposeKnowledgeEntry(value)); setMessage(''); }
  async function confirmCandidate() { if (!candidate) return; const createdAt = candidate.createdAt; const next = { ...state, entries: [candidate, ...state.entries], messages: [...state.messages, { role: 'user', content: candidate.content, createdAt }, { role: 'assistant', content: respondToKnowledge(candidate.content, fixture), createdAt }] }; await save(next); onSend(candidate.title); setCandidate(null); setNotice('ナレッジに追加しました。'); }
  async function addFile(event) { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; try { const metadata = createLocalUploadMetadata(file); await repositoryRef.current.add(metadata); setDocuments(repositoryRef.current.list().filter((item) => item.state !== 'deleted')); await onAssetAdded(metadata); setNotice('ファイルのメタデータを追加しました。本文は保存・送信しません。'); } catch (error) { setNotice(error.message); } }
  async function confirmRemoval() { const target = removeRequested; if (!target) return; await repositoryRef.current.delete(target.id, target); setDocuments(repositoryRef.current.list().filter((item) => item.state !== 'deleted')); setRemoveRequested(null); setNotice('ファイルを一覧から削除しました。'); }
  return <section aria-labelledby="knowledge-heading" className="kadode-composer-layout mx-auto grid min-h-[calc(100vh-3rem)] w-full max-w-6xl gap-5 pb-36">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[var(--color-text-muted)]">Knowledge</p><h1 id="knowledge-heading" className="mt-2 text-3xl font-semibold tracking-tight">ナレッジライブラリ</h1><p className="mt-2 text-sm text-[var(--color-text-muted)]">判断・会話・資料を、検索して時系列で振り返れます。</p></div><div><label htmlFor="knowledge-file-picker" className="sr-only">追加するファイルを選択</label><input ref={fileInputRef} id="knowledge-file-picker" className="sr-only" type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={(event) => void addFile(event)} /><Button type="button" className="gap-2" onClick={() => fileInputRef.current?.click()}><Upload className="size-4" />ファイルを追加</Button></div></header>
    {notice && <p role="status" className="text-sm text-[var(--color-text-muted)]">{notice}</p>}
    <div className="flex flex-wrap items-center gap-2" aria-label="ナレッジのカテゴリ">{Object.entries(categoryLabel).map(([key, label]) => <Button key={key} type="button" aria-pressed={category === key} variant={category === key ? 'default' : 'secondary'} className="min-h-8 px-3 text-xs" onClick={() => setCategory(key)}>{label}</Button>)}<label className="ml-auto flex min-w-[14rem] items-center gap-2 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-raised)] px-3 py-2 text-sm"><Search className="size-4" /><span className="sr-only">ナレッジを検索</span><input value={query} onChange={(event) => setQuery(event.target.value)} className="min-w-0 flex-1 bg-transparent outline-none" placeholder="タイトル・本文を検索" /></label></div>
    {archiveHistory.length > 0 && <h2 className="text-sm font-semibold text-[var(--color-text-muted)]">アーカイブ履歴</h2>}<ol aria-label="ナレッジ一覧" className="grid gap-2">{items.length ? items.map((item) => <li key={item.id}><Card className="flex items-start gap-3 p-3"><Badge variant="outline">{categoryLabel[item.category]}</Badge><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-semibold">{item.title}</h2><p className="mt-1 line-clamp-1 text-xs text-[var(--color-text-muted)]">{item.content}</p><div className="mt-2 flex flex-wrap items-center gap-1 text-xs text-[var(--color-text-muted)]"><Badge variant="outline">{sourceLabel[item.sourceType] ?? sourceLabel.unknown}</Badge><Badge variant="outline">確度: {confidenceLabel[item.confidence] ?? confidenceLabel.unknown}</Badge>{item.projectId && <Button type="button" variant="ghost" className="min-h-11 px-3 text-xs" onClick={() => onOpenProject()}>Projectを開く</Button>}</div></div><time className="shrink-0 text-xs text-[var(--color-text-muted)]">{dateText(item.updatedAt)}</time>{item.category === 'file' && item.id.startsWith('local-file:') && <Button type="button" variant="ghost" className="min-h-8 px-2 text-xs" onClick={() => setRemoveRequested(item)}>削除</Button>}</Card></li>) : <li><Card className="p-5 text-sm text-[var(--color-text-muted)]">条件に合うナレッジはまだありません。</Card></li>}</ol>
    <Dialog open={Boolean(candidate)} onOpenChange={(open) => !open && setCandidate(null)}><DialogContent><DialogTitle>ナレッジに追加しますか？</DialogTitle>{candidate && <><DialogDescription className="mt-2">AIが分類とタイトル案を作成しました。保存前に確認できます。</DialogDescription><p className="mt-4 text-sm"><Badge variant="outline">{categoryLabel[candidate.category]}</Badge></p><p className="mt-2 font-semibold">{candidate.title}</p><p className="mt-2 text-sm text-[var(--color-text-muted)]">{candidate.content}</p></>}<div className="mt-5 flex gap-2"><Button onClick={() => void confirmCandidate()}>ナレッジに追加</Button><DialogClose asChild><Button variant="secondary">キャンセル</Button></DialogClose></div></DialogContent></Dialog>
    <Dialog open={Boolean(removeRequested)} onOpenChange={(open) => !open && setRemoveRequested(null)}><DialogContent><DialogTitle>このファイルを削除しますか？</DialogTitle><DialogDescription>ファイル名と端末内メタデータを一覧から削除します。</DialogDescription><div className="mt-5 flex gap-2"><Button onClick={() => void confirmRemoval()}>削除を確定</Button><DialogClose asChild><Button variant="secondary">キャンセル</Button></DialogClose></div></DialogContent></Dialog>
    <AiComposer id="knowledge-composer" label="KnowledgeについてKadode AIに相談" value={message} onValueChange={setMessage} onSubmit={submit} mode="anchored" className="mx-auto w-full max-w-4xl" textareaClassName="kadode-composer__textarea--compact" placeholder="追加したい情報はありますか？" modelKey={modelKey} models={models} onModelChange={onModelChange} sendAriaLabel="Knowledgeの質問を送信" sendIcon={<SendHorizontal className="size-4" />} />
  </section>;
}
