import { useState } from 'react';

const stateLabel = { processing: '解析中', searchable: '検索可能', failed: '解析に失敗' };

export function KnowledgeSurface({ fixture, onAddAsset = () => {}, onRemoveAsset = () => {}, onSend = () => {} }) {
  const [message, setMessage] = useState('');
  const [removeRequested, setRemoveRequested] = useState(false);
  const asset = fixture?.asset;
  const availableReferences = asset?.references?.filter((reference) => reference.status !== 'unavailable') ?? [];
  if (!fixture || !asset || asset.state === 'deleted') return <section aria-labelledby="knowledge-heading" className="w-full max-w-3xl"><p className="text-xs font-bold tracking-[0.16em] text-stone-500">Knowledge</p><h1 id="knowledge-heading" className="mt-2 text-2xl font-semibold">Knowledge</h1><p className="mt-3 text-sm text-stone-600">参照できる資料はありません。</p><button type="button" onClick={onAddAsset} className="mt-5 min-h-11 rounded-full bg-stone-900 px-4 py-2 text-sm font-bold text-white">資料を追加</button></section>;
  function submit(event) { event.preventDefault(); if (message.trim()) { onSend(message.trim()); setMessage(''); } }
  return <section aria-labelledby="knowledge-heading" className="w-full max-w-3xl space-y-5">
    <div><p className="text-xs font-bold tracking-[0.16em] text-stone-500">Knowledge</p><h1 id="knowledge-heading" className="mt-2 text-2xl font-semibold">資料と判断を確認する</h1><p className="mt-2 text-sm leading-6 text-stone-600">本人のspaceに保存された根拠を、Projectの文脈と一緒に確認できます。</p>{fixture.provenance?.status === 'synthetic_demo' && <p className="mt-2 text-xs text-stone-500">{fixture.provenance.notice}</p>}</div>
    <article className="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-bold">{asset.name}</h2><p className="mt-1 text-sm text-stone-600">v{asset.version} · {stateLabel[asset.state] ?? asset.state}</p></div><button type="button" onClick={() => setRemoveRequested(true)} className="min-h-11 rounded-full border border-red-200 px-4 py-2 text-sm font-bold text-red-800">削除</button></div>{availableReferences.length > 0 && <ul aria-label="利用可能な出典" className="mt-4 grid gap-1 text-sm text-stone-600">{availableReferences.map((reference) => <li key={`${reference.kind}-${reference.sourceId}-${reference.locator}`}>{reference.kind}: {reference.sourceId} · {reference.locator}</li>)}</ul>}</article>
    <section aria-labelledby="project-context-heading" className="rounded-2xl border border-stone-200 bg-white p-5"><h2 id="project-context-heading" className="text-lg font-bold">Projectの背景</h2><p className="mt-3 text-sm font-semibold">{fixture.project.name}</p><p className="mt-1 text-sm leading-6 text-stone-600">{fixture.project.summary}</p><h3 className="mt-5 text-sm font-bold">今回の意思決定</h3><dl className="mt-2 grid gap-2 text-sm"><div><dt className="font-semibold text-stone-500">背景</dt><dd>{fixture.decision.background}</dd></div><div><dt className="font-semibold text-stone-500">本人判断</dt><dd>{fixture.decision.judgement}</dd></div><div><dt className="font-semibold text-stone-500">理由</dt><dd>{fixture.decision.reason}</dd></div></dl></section>
    {removeRequested && <div role="dialog" aria-modal="true" aria-labelledby="knowledge-delete-heading" className="rounded-2xl border border-red-200 bg-red-50 p-4"><h2 id="knowledge-delete-heading" className="font-bold">資料を削除しますか？</h2><p className="mt-1 text-sm">原本、抽出本文、断片、埋め込みを検索対象から外します。</p><button type="button" onClick={() => { onRemoveAsset(asset.id); setRemoveRequested(false); }} className="mt-3 min-h-11 rounded-full bg-red-800 px-4 py-2 text-sm font-bold text-white">削除を確定</button><button type="button" onClick={() => setRemoveRequested(false)} className="ml-3 min-h-11 text-sm underline">戻る</button></div>}
    <form onSubmit={submit} className="rounded-2xl border border-stone-200 bg-white p-4"><label htmlFor="knowledge-composer" className="sr-only">KnowledgeについてKadode AIに相談</label><textarea id="knowledge-composer" value={message} onChange={(event) => setMessage(event.target.value)} aria-describedby="knowledge-composer-hint" className="min-h-24 w-full resize-y rounded-lg border border-stone-200 p-3 text-base leading-6 outline-none" placeholder="資料について考えていることを入力" /><p id="knowledge-composer-hint" className="mt-2 text-xs text-stone-500">Enterで送信、Shift+Enterで改行</p><div className="mt-2 flex justify-end"><button type="submit" className="min-h-11 rounded-full bg-stone-900 px-5 py-2 text-sm font-bold text-white">Kadode AIに送る</button></div></form>
  </section>;
}
