import { demoProjectFixture } from './projectDemoFixtureAdapter';

const sectionLabels = ['事業', '市場', '競合', '利益', '実現性'];

export function ProjectSurface({ state = 'populated', project = demoProjectFixture }) {
  const status = { loading: '読み込み中', error: '確認できません', empty: '確認待ち', populated: project.status }[state];
  return <section aria-labelledby="project-surface-heading" className="max-w-3xl">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-stone-500">Project</p><h1 id="project-surface-heading" className="mt-2 text-2xl font-semibold tracking-tight">{project.name}</h1><p className="mt-1 text-sm text-stone-600">管理者デモ · 採用済み案件</p></div><span role="status" className="rounded-full border border-stone-300 px-3 py-1 text-xs font-semibold text-stone-600">{status}</span></div>
    <form className="mt-5 rounded-xl border border-stone-300 bg-white p-3 shadow-sm" aria-label="Project Kadode AI composer"><label htmlFor="project-composer" className="text-sm font-semibold">Project Kadode AI</label><textarea id="project-composer" aria-describedby="project-composer-hint" className="mt-2 min-h-20 w-full resize-y rounded-md border border-stone-200 p-2 text-base leading-6 outline-none focus-visible:ring-2 focus-visible:ring-stone-900" placeholder="この案件について聞いてみる" /><p id="project-composer-hint" className="mt-2 text-xs text-stone-500">Enterで送信 · Shift+Enterで改行</p><div className="mt-2 flex justify-end"><button type="button" className="min-h-11 rounded-md bg-stone-900 px-5 py-2 text-sm font-bold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-stone-900">送信</button></div></form>
    <div className="mt-5 grid gap-2" aria-label="事業評価の観点">{sectionLabels.map((label) => { const item = project.sections[label]; return <article key={label} className="rounded-xl border border-stone-200 bg-white px-4 py-3 shadow-sm"><div className="flex flex-wrap items-baseline justify-between gap-2"><h2 className="text-sm font-bold">{label}</h2><span className="text-xs font-semibold text-stone-500">{item.status}</span></div><p className="mt-1 text-sm text-stone-700">{state === 'loading' ? '読み込み中です。' : state === 'error' ? '現在確認できません。' : item.summary}</p><p className="mt-2 text-xs text-stone-500"><span className="font-semibold text-stone-600">根拠:</span> {item.evidence} · <span className="font-semibold text-stone-600">未確定:</span> {item.unknown}</p></article>; })}</div>
  </section>;
}
