export const PLAN = Object.freeze({
  FREE: 'free',
  STANDARD: 'standard',
});

export const MODEL_CATALOG = Object.freeze([
  Object.freeze({
    logicalKey: 'claude-haiku-4-5',
    displayName: 'Claude Haiku 4.5',
    provider: 'anthropic',
    modelId: 'claude-haiku-4-5-20251001',
    plans: [PLAN.FREE, PLAN.STANDARD],
    reasoningModes: [],
    capabilities: ['idea-draft'],
    costClass: 'lightweight',
    enabled: true,
    isDefault: false,
  }),
  Object.freeze({
    logicalKey: 'gpt-5.6-terra',
    displayName: 'GPT-5.6 Terra',
    provider: 'openai',
    modelId: 'gpt-5.6-terra',
    plans: [PLAN.STANDARD],
    reasoningModes: ['low', 'medium', 'high'],
    capabilities: ['idea-draft'],
    costClass: 'standard',
    enabled: true,
    isDefault: true,
  }),
  Object.freeze({
    logicalKey: 'claude-sonnet-5',
    displayName: 'Claude Sonnet 5',
    provider: 'anthropic',
    modelId: 'claude-sonnet-5',
    plans: [PLAN.STANDARD],
    reasoningModes: [],
    capabilities: ['idea-draft'],
    costClass: 'standard',
    enabled: true,
    isDefault: false,
  }),
  Object.freeze({
    logicalKey: 'claude-opus-5',
    displayName: 'Claude Opus 5',
    provider: 'anthropic',
    modelId: 'claude-opus-5',
    plans: [PLAN.STANDARD],
    reasoningModes: [],
    capabilities: ['idea-draft'],
    costClass: 'premium',
    enabled: true,
    isDefault: false,
  }),
]);
